ttsx/text/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^list([0-9]*)/$',views.list,name ='list'),
    url(r'^detail(?P<id>[0-9]+)/$',views.detail,name ='detail'),
    # url(r'detail/$',views.detail,name = 'detail'),
    url(r'^base/$',views.base,name='base'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^place_order/$',views.place_order,name='place_order'),
    url(r'^cart/$',views.cart,name='cart'),
    url(r'^success/$',views.success,name='success'),
]

ttsx/ttsx/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
	url(r'^tinymce/', include('tinymce.urls')),
	url(r'^',include('text.urls',namespace='main')),
    url(r'^search/', include('haystack.urls')),
]

ttsx/text/models.py
from django.db import models
from tinymce.models import HTMLField

class User_db(models.Model):

	user_name = models.CharField(max_length=20)
	user_password = models.CharField(max_length=20)
	user_phone = models.CharField(max_length=20)
	user_email = models.CharField(max_length=20)
	user_address = HTMLField()
	def __str__(self):
		return self.user_name.encode('utf-8')

	class Meta():
		db_table = 'User_db'


class Ord(models.Model):

	order_user_id = models.ForeignKey('User_db')
	order_num = models.IntegerField(default=0)
	submit_date = models.DateTimeField()
	total_price = models.DecimalField(max_digits=20,decimal_places=2)
	isPay = models.BooleanField(default=0)
	def __str__(self):
		order_num = str(self.order_num)
		return order_num.encode('utf-8')

	class Meta():
		db_table = 'Ord'


class Order_detail(models.Model):

	odetail_goods_id = models.ForeignKey('Goods_info')
	odetail_goods_num = models.IntegerField(default=0)
	odetail_totalprice = models.IntegerField(default=0)
	detail_num = models.ForeignKey('Ord')

	class Meta():
		db_table = 'Order_detail'


class Goods_list(models.Model):

	goods_list_name = models.CharField(max_length=20)
	goods_list_class = models.CharField(max_length=20)
	goods_list_pic = models.ImageField(upload_to='uploads/')

	def __str__(self):
		return self.goods_list_name.encode('utf-8')


	class Meta():
		db_table = 'Goods_list'


class Cart(models.Model):

	goods_num = models.IntegerField()
	user_id = models.ForeignKey('User_db')
	goods_id = models.ForeignKey('Goods_info')

	class Meta():
		db_table = 'Cart'


class Goods_info(models.Model):

    goods_name = models.CharField(max_length=20)
    goods_description = HTMLField()
    goods_price = models.DecimalField(max_digits=10,decimal_places=2)
    goods_stock = models.IntegerField()
    goods_msg = HTMLField()
    goods_unit = models.CharField(max_length=20)
    goods_list_id=models.ForeignKey('Goods_list')
    goods_pic_url=models.ImageField(upload_to='uploads/')

    def __str__(self):
    	return self.goods_name.encode('utf-8')
    class Meta():
        db_table = 'Goods_info'



class Receiver(models.Model):

    receiver_address = HTMLField()
    receiver_name = models.CharField(max_length=20)
    receiver_phone = models.CharField(max_length=20)
    receiver_user_id = models.ForeignKey('User_db')
    receiver_email = models.CharField(max_length=20)
    
    class Meta():
    	db_table = 'Receiver'

ttsx/text/views.py
# coding=utf-8
from django.shortcuts import render
from django.http import *
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from models import *
from .decrator import *
# Create your views here.

@view_name
def index(request,dic):
	goods_list = Goods_list.objects.all()

	fruit = goods_list[0]
	count = fruit.goods_info_set.count()
	num = count - 4
	fruit_four = fruit.goods_info_set.filter(id__gte=num)
	fruit_show = fruit.goods_info_set.all()[1:4]

	seafood = goods_list[1]
	count = seafood.goods_info_set.count()
	num = count - 4
	seafood_four = seafood.goods_info_set.filter(id__gte=num)
	seafood_show = seafood.goods_info_set.all()[1:4]

	meet = goods_list[2]
	count = meet.goods_info_set.count()
	num = count - 4
	meet_four = meet.goods_info_set.filter(id__gte=num)
	meet_show = meet.goods_info_set.all()[1:4]

	egg = goods_list[3]
	count = egg.goods_info_set.count()
	num = count - 4
	egg_four = egg.goods_info_set.filter(id__gte=num)
	egg_show = egg.goods_info_set.all()[1:4]

	vegetables = goods_list[4]
	count = vegetables.goods_info_set.count()
	num = count - 4
	vegetables_four = vegetables.goods_info_set.filter(id__gte=num)
	vegetables_show = vegetables.goods_info_set.all()[1:4]

	ice = goods_list[5]
	count = ice.goods_info_set.count()
	num = count - 4
	ice_four = ice.goods_info_set.filter(id__gte=num)
	ice_show = ice.goods_info_set.all()[1:4]

	request.session['uname']='张三'
	uname = request.session['uname']
	
	#将购物车里的所有商品数量显示
	cart = Cart.objects.all()
	goods_count = 0
	for cart_one in cart:
		goods_count += cart_one.goods_num
	dic['goods_count'] = goods_count
	#商品分类列表
	dic['goods_list'] = goods_list
	dic['fruit_four']=fruit_four
	dic['fruit_show']=fruit_show
	dic['fruit']=fruit
	dic['seafood_four']=seafood_four
	dic['seafood_show']=seafood_show
	dic['seafood']=seafood
	dic['meet_four']=meet_four
	dic['meet_show']=meet_show
	dic['seafood']=seafood
	dic['meet_four']=meet_four
	dic['meet_show']=meet_show
	dic['meet']=meet
	dic['egg']=egg
	dic['vegetables_four']=vegetables_four
	dic['vegetables_show']=vegetables_show
	dic['vegetables']=vegetables
	dic['ice_four']=ice_four
	dic['ice_show']=ice_show
	dic['ice']=ice
	#获取用户名通过session
	dic['data']=uname
	return render(request, 'text/index.html', dic)


def list(request, id):
	return render(request, 'text/list.html')


# def detail(request, id):
#     dic = {'id': id}
#     return render(request, 'text/detail.html', dic)
@view_name
def detail(request,dic,id):
	#商品列表
	goods_list = Goods_list.objects.all()
	#单个商品详情
	goods = Goods_info.objects.get(pk=id)
	dic['goods']=goods
	dic['goods_list']=goods_list
	dic['list_id'] = goods.goods_list_id_id
	dic['list_name'] = goods.goods_list_id.goods_list_name
	dic['goods_info'] =Goods_info.objects.all().order_by('-id')[0:2]
	#获取购物车所有商品的数量
	cart = Cart.objects.all()
	goods_count = 0
	for cart_one in cart:
		goods_count += cart_one.goods_num
	dic['goods_count'] = goods_count
	return render(request,'text/detail.html',dic)

def base(request):
	return render(request, 'text/base.html')


def logout(request):
	del request.session['uname']
	return redirect(reverse('main:index'))

def place_order(request, order_num=1232,cart_id = [1,2]):
	#测试
	name = 'name'
	# name = request.session.get('uname')
	user = User_db.objects.get(user_name=name)
	receiver = user.receiver_set.last()
	address = receiver.receiver_address
	rece_name = receiver.receiver_name
	rece_phone = receiver.receiver_phone
	# 获取订单号对应的订单表信息
	user_ord = Ord.objects.get(order_num=order_num)
	# 通过对象获得订单号对应的的用户名
	uname = user_ord.order_user_id.user_name
	#判断cart_id的对应的购物车的用户和session对应的name是不是一样

	# 如果名字一样，则订单号和用户匹配，找订单号对应的商品
	if uname == name:
		# 获取订单详情里面最新的一条
		dorder = user_ord.order_detail_set.last()
		goods_num = dorder.odetail_goods_num
		pre_price = dorder.odetail_totalprice
		# goods = dorder.odetail_goods_id
		total_price = user_ord.total_price
		cart = user.cart_set.filter(pk__in=cart_id)
		# total_price = (goods.goods_price)*goods_num
		dic = {
				'address': address,
				'rece_name': rece_name,
				'rece_phone': rece_phone,
				'goods_num':goods_num,
				# 'goods':goods,
				'total_price':total_price,
				'cart':cart,
			   }
		return render(request, 'text/place_order.html', dic)

def cart(request):
	return render(request,'text/cart.html')
def success(request):
	return render(request,'text/success.html')

ttsx/templates/text/detail.html
{%extends 'text/base.html'%}
{%block title%}天天生鲜-详细页{%endblock title%}
{%block script%}
	<script type="text/javascript">
    $(function(){
        $('.add').click(function(){
            var add_num = $(this).prev().val();
            add_num = parseInt(add_num) + 1;
            $(this).prev().val(add_num);  
            var total_price = $(this).prev().val() * ({{goods.goods_price}}*100)/100;
        	$('.total > em').text(total_price.toFixed(2)); 
        });
        $('.minus').click(function(){
        	var minus_num = $(this).prev().prev().val();
        	if(parseInt(minus_num)>1){
        		minus_num = parseInt(minus_num) - 1;
        	}
        	$(this).prev().prev().val(minus_num);
        	var total_price = parseFloat($(this).prev().prev().val()) * ({{goods.goods_price}}*100)/100;
        	$('.total > em').text(total_price.toFixed(2));
        });
        $('.num_show').blur(function(){
        	var price = parseFloat({{goods.goods_price}})
        	var value = parseInt($(this).val())
        	if(value <1|isNaN(value)){
        		$(this).val(1);
        		var total_price = $(this).val() * (price*100)/100
        		$('.total > em').text(total_price.toFixed(2));
        		
        	}else{
        		$(this).val(value)
        		var total_price = value * (price*100)/100
        		$('.total > em').text(total_price.toFixed(2));
        	};
        	
        });
        $('.detail_tab li').click(function(){
        	$(this).addClass('active');
        	$(this).siblings().removeClass('active');
        });
        $('#add_cart').click(function(){
        	var value = parseInt($('.num_show').val()) + parseInt({{goods_count}});
        	$('#show_count').text(value);
        })
    })
    </script>
{%endblock script%}
{%block cart%}
        <div class="guest_cart fr">
            <a href="{%url 'main:index'%}" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">{{goods_count}}</div>
        </div>
        {%endblock cart%}
{%block content%}
{%load static from staticfiles%}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					{%for list in goods_list%}
					<li><a href="{%url 'main:list' list.id%}" class="{{list.goods_list_class}}">{{list.goods_list_name}}</a></li>
					{%endfor%}
					
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{%url 'main:index'%}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="{%url 'main:index'%}">全部分类</a>
		<span>></span>
		<a href="{%url 'main:list' list_id%}">{{list_name}}</a>
		<span>></span>
		<a href="#goodsdetail">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{%static goods.goods_pic_url%}"></div>

		<div class="goods_detail_list fr">
			<h3>{{goods.goods_name}}</h3>
			<p>{{goods.goods_description|safe}}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{goods.goods_price}}</em></span>
				<span class="show_unit">单  位：{{goods.goods_unit}}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>
				</div> 
				<div class="num_stock fr">库存:&nbsp;&nbsp;{{goods.goods_stock}}&nbsp;&nbsp;个</div>
			</div>
			<div class="total">总价：<em>{{goods.goods_price}}</em>&nbsp;&nbsp;元</div>
			<div class="operate_btn">
				<a href="{%url 'main:place_order'%}" class="buy_btn">立即购买</a>
				<a href="{%url 'main:cart'%}" class="add_cart" id="add_cart">加入购物车</a>				
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					{%for goods_one in goods_info%}
					<li>
						<a href="{%url 'main:detail' goods_one.id%}"><img src="{%static goods_one.goods_pic_url%}"></a>
						<h4><a href="#">{{goods_one.goods_name}}</a></h4>
						<div class="prize">￥{{goods_one.goods_price}}</div>
					</li>
					{%endfor%}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li >评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt id='goodsdetail'>商品详情：</dt>
					<dd>{{goods.goods_msg|safe}} </dd>
				</dl>
			</div>

		</div>
	</div>
{%endblock content%}
{%block button%}
<!--<div class="add_jump"></div>

	
	<script type="text/javascript">
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
		$('#add_cart').click(function(){
			$(".add_jump").stop().animate({
				'left': $to_y+7,
				'top': $to_x+7},
				"fast", function() {
					$(".add_jump").fadeOut('fast',function(){
						$('#show_count').html(2);
					});

			});
		})
	</script>-->
{%endblock button%}

ttsx/templates/text/index.html
{%extends 'text/base.html'%}
{%block cart%}
        <div class="guest_cart fr">
            <a href="{%url 'main:index'%}" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">{{goods_count}}</div>
        </div>
        {%endblock cart%}
{%block content%}
		<div class="navbar_con">
        <div class="navbar">
            <h1 class="fl">全部商品分类</h1>
            <ul class="navlist fl">
                <li><a href="{%url 'main:index'%}">首页</a></li>
                <li class="interval">|</li>
            <li><a href="{%url 'main:place_order'%}">手机生鲜</a></li>
                <li class="interval">|</li>
            <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>
{%block left%}
{%load static from staticfiles%}

	<div class="center_con clearfix">
		<ul class="subnav fl">
			{%for list in goods_list%}
			<li><a href="#model0{{list.id}}" class="{{list.goods_list_class}}">{{list.goods_list_name}}</a></li>
			{%endfor%}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li>
				<img src="{%static 'text/images/slide.jpg'%}" alt="幻灯片">
				<!-- <img src="/static/{{data.goods_list_pic}}" alt="幻灯片"> --></li>
				<!-- <li><img src="{%static 'text/images/slide01.jpg'%}" alt="幻灯片"></li> -->

				<li><img src="{%static 'text/images/slide02.jpg'%}" alt="幻灯片"></li>
				<li><img src="{%static 'text/images/slide03.jpg'%}" alt="幻灯片"></li>
				<li><img src="{%static 'text/images/slide04.jpg'%}" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="/"><img src="{%static 'text/images/adv01.jpg'%}" alt="广告"></a>
			<a href="/"><img src="{%static 'text/images/adv01.jpg'%}" alt="广告"></a>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">{{fruit.goods_list_name}}</h3>
			<div class="subtitle fl">
				<span>|</span>
				{%for name in fruit_show%}
				<a href="{%url 'main:detail' name.id%}">{{name.goods_name}}</a>
				{%endfor%}
			</div>
			<a href="{%url 'main:list' fruit.id%}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{%static fruit.goods_list_pic%}"></div>
			<ul class="goods_list fl">
				{%for good in fruit_four%}
				<li>
					<h4><a href="{%url 'main:detail' good.id%}">{{good.goods_name}}</a></h4>
					<a href="{%url 'main:detail' good.id%}"><img src="{%static good.goods_pic_url%}"></a>
					<div class="prize">¥ {{good.goods_price}}</div>
				</li>
				{%endfor%}
			</ul>
		</div>
	</div>


	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model02">{{seafood.goods_list_name}}</h3>
			<div class="subtitle fl">
				<span>|</span>
				<!-- {%for name in fruit_show%}
				<a href="{%url 'main:detail' name.id%}">{{name.goods_name}}</a>
				{%endfor%} -->
				<a href="#">河虾</a>
				<a href="#">扇贝</a>				
			</div>
			<a href="{%url 'main:list' fruit.id%}" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{%static seafood.goods_list_pic%}"></div>
			<ul class="goods_list fl">
			<!-- {%for good in seafood_four%}
				<li>
					<h4><a href="{%url 'main:detail' good.id%}">{{good.goods_name}}</a></h4>
					<a href="{%url 'main:detail' good.id%}"><img src="{%static good.goods_pic_url%}"></a>
					<div class="prize">¥ {{good.goods_price}}</div>
				</li>
				{%endfor%} -->

				<li>
					<h4><a href="#">青岛野生海捕大青虾</a></h4>
					<a href="#"><img src="{%static 'text/images/goods/goods018.jpg'%}"></a>
					<div class="prize">¥ 48.00</div>
				</li>
				<li>
					<h4><a href="#">扇贝</a></h4>
					<a href="#"><img src="{%static 'text/images/goods/goods019.jpg'%}"></a>
					<div class="prize">¥ 46.00</div>
				</li>
				<li>
					<h4><a href="#">冷冻秋刀鱼</a></h4>
					<a href="#"><img src="{%static 'text/images/goods/goods020.jpg'%}"></a>
					<div class="prize">¥ 19.00</div>
				</li>
				<li>
					<h4><a href="#">基围虾</a></h4>
					<a href="#"><img src="{%static 'text/images/goods/goods021.jpg'%}"></a>
					<div class="prize">¥ 25.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model03">{{meet.goods_list_name}}</h3>
			<div class="subtitle fl">
				<span>|</span>
				<!-- {%for name in meet_show%}
				<a href="{%url 'main:detail' name.id%}">{{name.goods_name}}</a>
				{%endfor%} -->
				<a href="">澳洲牛肉</a>
				<a href="">乌克兰大白猪</a>
			</div>
			<a href="{%url 'main:list' meet.id%}" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{%static meet.goods_list_pic%}"></div>
			<ul class="goods_list fl">
				<!-- {%for good in seafood_four%}
				<li>
					<h4><a href="{%url 'main:detail' good.id%}">{{good.goods_name}}</a></h4>
					<a href="{%url 'main:detail' good.id%}"><img src="{%static good.goods_pic_url%}"></a>
					<div class="prize">¥ {{good.goods_price}}</div>
				</li>
				{%endfor%} -->

				<li>
					<h4><a href="#">万年豚有机土猪精</a></h4>
					<a href="#"><img src="{%static 'text/images/goods/goods022.png'%}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="{%static 'text/images/goods/goods023.png'%}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="{%static 'text/images/goods/goods024.png'%}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="{%static 'text/images/goods/goods025.png'%}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model04">{{egg.goods_list_name}}</h3>
			<div class="subtitle fl">
				<span>|</span>
				<!-- {%for name in egg_show%}
				<a href="{%url 'main:detail' name.id%}">{{name.goods_name}}</a>
				{%endfor%} -->
				<a href="#">鲜芒</a>
				<a href="#">加州提子</a>
				<a href="#">亚马逊牛油果</a>
			</div>
			<a href="{%url 'main:list' egg.id%}" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{%static egg.goods_list_pic%}"></div>
			<ul class="goods_list fl">
			<!-- {%for good in egg_four%}
				<li>
					<h4><a href="{%url 'main:detail' good.id%}">{{good.goods_name}}</a></h4>
					<a href="{%url 'main:detail' good.id%}"><img src="{%static good.goods_pic_url%}"></a>
					<div class="prize">¥ {{good.goods_price}}</div>
				</li>
				{%endfor%} -->

				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="{%static 'text/images/goods/goods026.png'%}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="{%static 'text/images/goods/goods027.png'%}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="{%static 'text/images/goods/goods028.png'%}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="{%static 'text/images/goods/goods029.png'%}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model05">{{vegetables.goods_list_name}}</h3>
			<div class="subtitle fl">
				<span>|</span>
				<!-- {%for name in vegetables_show%}
				<a href="{%url 'main:detail' name.id%}">{{name.goods_name}}</a>
				{%endfor%} -->
				<a href="#">鲜芒</a>
				<a href="#">加州提子</a>
				<a href="#">亚马逊牛油果</a>
			</div>
			<a href="{%url 'main:list' vegetables.id%}" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{%static vegetables.goods_list_pic%}"></div>
			<ul class="goods_list fl">
				<!-- {%for good in vegetables_four%}
				<li>
					<h4><a href="{%url 'main:detail' good.id%}">{{good.goods_name}}</a></h4>
					<a href="{%url 'main:detail' good.id%}"><img src="{%static good.goods_pic_url%}"></a>
					<div class="prize">¥ {{good.goods_price}}</div>
				</li>
				{%endfor%} -->
				<li>
					<h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>
					<a href="#"><img src="{%static 'text/images/goods/goods040.png'%}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="{%static 'text/images/goods/goods041.png'%}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="{%static 'text/images/goods/goods042.png'%}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="{%static 'text/images/goods/goods043.png'%}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model06">{{egg.goods_list_name}}</h3>
			<div class="subtitle fl">
				<span>|</span>
				<!-- {%for name in ice_show%}
				<a href="{%url 'main:detail' name.id%}">{{name.goods_name}}</a>
				{%endfor%} -->
				<a href="#">鲜芒</a>
				<a href="#">加州提子</a>
				<a href="#">亚马逊牛油果</a>
			</div>
			<a href="{%url 'main:list' ice.id%}" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{%static ice.goods_list_pic%}"></div>
			<ul class="goods_list fl">
				<!-- {%for good in ice_four%}
				<li>
					<h4><a href="{%url 'main:detail' good.id%}">{{good.goods_name}}</a></h4>
					<a href="{%url 'main:detail' good.id%}"><img src="{%static good.goods_pic_url%}"></a>
					<div class="prize">¥ {{good.goods_price}}</div>
				</li>
				{%endfor%} -->
				<li>
					<h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>
					<a href="#"><img src="{%static 'text/images/goods/goods044.png'%}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="{%static 'text/images/goods/goods045.png'%}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="{%static 'text/images/goods/goods046.png'%}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">维多利亚葡萄</a></h4>
					<a href="#"><img src="{%static 'text/images/goods/goods047.png'%}"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>
{%endblock left%}
{%endblock content%}


ttsx/templates/text/success.html
{%extends 'text/base.html'%}
{%block content%}
<div style='font-size:30px;margin:50px auto;width:300px;height:330px;'>支付成功!</div>
{%endblock content%}